Added task-dependency data model
Real-Dev-Squad/website-data-models pull request #46
Opened 2023-05-24 00:50 UTC by vinit717

close #45

2023-05-25 01:12 UTC, sahsisunny approved these changes

2023-05-27 06:02 UTC, heyrandhir requested changes

2023-05-27 06:02 UTC, heyrandhir commented on task-dependency/README.md
> +}
```suggestion
{
  "taskId" : "Id of the task which has dependencies.",
  "dependsId" : "Id of the task which the task is dependent on."
}

2023-05-27 06:05 UTC, vinit717 commented on task-dependency/README.md
> +}
done

2023-05-27 06:11 UTC, heyrandhir submitted a review, later dismissed

2023-05-27 06:12 UTC, heyrandhir reviewed
Description please

2023-05-27 06:12 UTC, RitikJaiswal75 requested changes

2023-05-27 06:12 UTC, RitikJaiswal75 commented on task-dependency/README.md
> +  "dependsId" : "Id of the task which the task is dependent on."
please change the name of the key

2023-05-27 06:12 UTC, RitikJaiswal75 commented on task-dependency/README.md
> +  "dependsId" : "bIkwsOXXWNOjU2bGQ64Y",
please change this key

2023-05-27 06:16 UTC, vinit717 commented on task-dependency/README.md
> +  "dependsId" : "bIkwsOXXWNOjU2bGQ64Y",
done

2023-05-27 06:16 UTC, vinit717 commented on task-dependency/README.md
> +  "dependsId" : "Id of the task which the task is dependent on."
done

2023-05-27 07:05 UTC, RitikJaiswal75 approved these changes

2023-05-27 07:07 UTC, sahsisunny approved these changes

2023-05-27 10:17 UTC, heyrandhir approved these changes

2023-05-28 06:15 UTC, merged